---
name: Notify Deployoholics
description: Send a message to the Deployoholics Wire channel.

inputs:
  text:
    description: Wire message text.
    required: true
  status:
    description: Wire notification status.
    required: false
    default: failure
  webhook-url:
    description: Wire webhook URL.
    required: true
  token:
    description: GitHub Actions token.
    required: true

runs:
  using: composite
  steps:
    - name: Send Wire notification
      uses: 
        wireapp/github-app/.github/actions/notify-wire@3a9c9d7e71d96d391951429c1d1bfbbee081ed8c
      with:
        webhook-url: ${{ inputs.webhook-url }}
        token: ${{ inputs.token }}
        text: |-
              ${{ inputs.status }}

              ${{ inputs.text }}
