---
name: Notify Deployoholics
description: Send a message to the Deployoholics Wire channel using the Deployoholics webhook and token.

inputs:
  text:
    description: Wire message text.
    required: true
  deployoholics-webhook-url:
    description: Wire webhook URL to notify Deployoholics conversation.
    required: true
  deployoholics-token:
    description: GitHub Actions token to notify Deployoholics conversation.
    required: true

runs:
  using: composite
  steps:
    - name: Send Wire notification
      uses: wireapp/github-app/.github/actions/notify-wire@3a9c9d7e71d96d391951429c1d1bfbbee081ed8c
      with:
        webhook-url: ${{ inputs.deployoholics-webhook-url }}
        token: ${{ inputs.deployoholics-token }}
        text: |-
          ${{ inputs.text }}
