# Types
'type: refactoring 🛠':
  title: '^refactor(\(.+\))?:.*'
'type: bug / fix 🐞':
  title: '^(run)?fix(\(.+\))?:.*'
'type: chore 🧹':
  title: '^chore(\(.+\))?:.*'
'type: documentation 📋':
  title: '^docs(\(.+\))?:.*'
'type: feature / request ✨':
  title: '^feat(\(.+\))?:.*'
'type: test 👷':
  title: '^test(\(.+\))?:.*'

# Sizes
'size: xs':
  size-below: 10
'size: s':
  size-above: 9
  size-below: 100
'size: m':
  size-above: 99
  size-below: 300
'size: l':
  size-above: 299
  size-below: 500
'size: xl':
  size-above: 499
  size-below: 1000
'size: xxl':
  size-above: 999

# Components
'comp: calling':
  files:
    - 'src/script/calling/.*'
'comp: preferences':
  files:
    - 'src/script/properties/.*'
'comp: infrastructure':
  files:
    - '.elasticbeanstalk'
    - '.github/.*'
