env:
  browser: true
  node: true
  es6: true
  jasmine: true

extends:
  "eslint:recommended"

globals:
  _: true
  $: true
  amplify: true
  cryptobox: true
  CryptoJS: true
  ko: true
  libsodium: true
  LRUCache: true
  moment: true
  pako: true
  platform: true
  Proteus: true
  Raygun: true
  twttr: true
  wire: true
  z: true

plugins:
  - jsdoc

rules:
  array-bracket-spacing: [2, never]
  arrow-parens: [2, always]
  arrow-spacing: 2
  block-spacing: 2
  brace-style: [2, 1tbs]
  comma-dangle: [2, always-multiline]
  comma-spacing: [2, {before: false, after: true}]
  comma-style: 2
  computed-property-spacing: 2
  constructor-super: 2
  default-case: 2
  eol-last: 2
  func-call-spacing: 2
  handle-callback-err: 2
  indent: [2, 2, {SwitchCase: 1}]
  jsdoc/require-hyphen-before-param-description: 2
  key-spacing: 2
  keyword-spacing: 2
  new-parens: 2
  newline-per-chained-call: [2, {ignoreChainWithDepth: 2}]
  no-console: 0
  no-const-assign: 2
  no-dupe-class-members: 2
  no-else-return: 2
  no-lonely-if: 2
  no-multi-spaces: 2
  no-shadow: 2
  no-unused-expressions: 2
  no-unused-vars: [2, {args: none}]
  no-var: 2
  no-whitespace-before-property: 2
  object-curly-spacing: [2, never]
  prefer-const: 2
  prefer-promise-reject-errors: 2
  prefer-spread: 2
  quotes: [2, single, avoid-escape]
  semi: [2, always]
  semi-spacing: [2, {before: false, after: true}]
  sort-keys: [2, asc, {caseSensitive: true, natural: true}]
  sort-vars: 2
  space-before-blocks: 2
  space-before-function-paren: [2, never]
  space-in-parens: [2, never]
  space-infix-ops: 2
  space-unary-ops: [2, {words: true, nonwords: false}]
  spaced-comment: [2, always, {exceptions: ["#"]}]
  strict: [2, global]
  valid-jsdoc: [2, {prefer: {return: returns}, requireParamDescription: true, requireReturnDescription: true}]
