ls:
  '{tools/build-artifact/verifyPublicProductionBundle.ts,libraries/core/src/messagingProtocols/mls/utils}':
    .ts: camelCase
  tools/build-artifact/verifyPublicProductionBundle.test.ts:
    .test.ts: camelCase
  libraries/config/src:
    .dir: camelCase
    .ts: camelCase
    .spec.ts: camelCase
    .config.ts: camelCase
    .config.spec.ts: camelCase
    .types.ts: camelCase
  '{apps/webapp/src/script/util/localizerUtil,apps/webapp/src/script/components/meeting,apps/webapp/src/script/repositories/media/backgroundEffects}':
    .dir: camelCase
    .ts: camelCase
    .tsx: camelCase
    .test.tsx: camelCase
    .types.ts: camelCase
  '{apps/webapp/src/script/util/connectionQualityHandler,apps/webapp/src/script/applicationPeriodicChecks,apps/webapp/src/script/browser,apps/webapp/src/script/repositories/entity/message,apps/webapp/src/script/repositories/assets,apps/webapp/src/script/repositories/audio,apps/webapp/src/script/repositories/backup,apps/webapp/src/script/repositories/cache,apps/webapp/src/script/repositories/cells,apps/webapp/src/script/repositories/connection,apps/webapp/src/script/repositories/search,apps/webapp/src/script/repositories/user,apps/webapp/src/script/service,apps/server/routes,apps/server/util,libraries/api-client/src/utils/backFromSleepHandler,libraries/api-client/src/obfuscation}':
    &a1
    .dir: camelCase
    .ts: camelCase
    .test.ts: camelCase
  '{libraries/api-client/src/auth,libraries/api-client/src/http,libraries/api-client/src/conversation,libraries/api-client/src/team/member,libraries/api-client/src,libraries/core/src/self,libraries/core/src/user,libraries/core/src/auth,libraries/core/src/linkPreview,libraries/core/src/cryptography,libraries/core/src/conversation/assetService,libraries/core/src/conversation/conversationMapper,libraries/core/src/conversation/messageTimer,libraries/core/src/conversation/subconversationService,libraries/core/src/messagingProtocols/proteus/proteusService/decryptionErrorGenerator,libraries/core/src/messagingProtocols/mls/recovery,libraries/core/src/messagingProtocols/mls}': *a1
  '{libraries/core/src/messagingProtocols/mls/eventHandler}': *a1
  apps/webapp/src/script/util:
    .ts: camelCase
    .tsx: camelCase
    .test.ts: camelCase
    .test.tsx: camelCase
  apps/webapp/src/script/util/test/mock:
    .ts: camelCase
    .mock.ts: camelCase
  '{apps/webapp/src/script/e2eIdentity,libraries/core/src/util}':
    .dir: camelCase
    .ts: camelCase
    .test.ts: camelCase
    .store.ts: camelCase
  apps/webapp/src/script/auth:
    .dir: camelCase
    .ts: camelCase
    .tsx: camelCase
    .test.ts: camelCase
    .test.tsx: camelCase
    .styles.ts: camelCase
    .styles.tsx: camelCase
  '{apps/webapp/src/script/cleanupStack,apps/webapp/src/script/clock,libraries/core/src}':
    .ts: camelCase
    .test.ts: camelCase
  '{apps/webapp/src/script/components/icon.tsx,apps/webapp/src/script/components/appNotification,apps/webapp/src/script/components/connectRequests}':
    .tsx: camelCase
  apps/webapp/src/script/components/appContainer:
    .dir: camelCase
    .tsx: camelCase
    .test.ts: camelCase
  '{apps/webapp/src/script/components/appLoader,apps/webapp/src/script/components/cellsGlobalView,apps/webapp/src/script/components/copyToClipboardButton,apps/webapp/src/script/components/draggableClickWrapper,apps/webapp/src/script/components/dropFileArea,apps/webapp/src/script/components/emojiPicker,apps/webapp/src/script/components/errorFallback,apps/webapp/src/script/components/fadingScrollbar,apps/webapp/src/script/components/fullscreenModal,apps/webapp/src/script/components/giphy,apps/webapp/src/script/components/historyExport,apps/webapp/src/script/components/historyImport,apps/webapp/src/script/components/image,apps/webapp/src/script/components/inViewport}':
    &a2
    .dir: camelCase
    .ts: camelCase
    .tsx: camelCase
    .test.tsx: camelCase
    .styles.ts: camelCase
  '{apps/webapp/src/script/components/panel,apps/webapp/src/script/components/panel/panelActions}': *a2
  '{apps/webapp/src/script/components/availabilityIcon,apps/webapp/src/script/components/configToolbar}':
    .tsx: camelCase
    .styles.tsx: camelCase
  apps/webapp/src/script/components/bannerPortal:
    .ts: camelCase
    .tsx: camelCase
    .styles.ts: camelCase
  apps/webapp/src/script/components/cells:
    .dir: camelCase
    .ts: camelCase
    .tsx: camelCase
    .test.ts: camelCase
    .test.tsx: camelCase
  apps/webapp/src/script/components/cellsSearchInput:
    .tsx: camelCase
    .styles.ts: camelCase
  apps/webapp/src/script/components/classifiedBar:
    .tsx: camelCase
    .test.tsx: camelCase
  '{apps/webapp/src/script/components/panel/conversationProtocolDetails,apps/webapp/src/script/ui}':
    .dir: camelCase
    .ts: camelCase
    .tsx: camelCase
    .test.tsx: camelCase
  apps/webapp/src/script/components/panel/singleAction:
    .dir: camelCase
    .ts: camelCase
    .tsx: camelCase
    .styles.ts: camelCase
  '{apps/webapp/src/script/message,apps/webapp/src/script/repositories/properties,apps/webapp/src/script/repositories/storage,apps/webapp/src/script/repositories/storage/record,apps/webapp/src/script/error,libraries/api-client/src/broadcast,libraries/api-client/src/env,libraries/api-client/src/generic,libraries/api-client/src/services,libraries/api-client/src/federation/data,libraries/api-client/src/giphy,libraries/api-client/src/validation,libraries/api-client/src/oauth,libraries/api-client/src/serviceProvider,libraries/api-client/src/connection,libraries/api-client/src/account,libraries/api-client/src/event,libraries/api-client/src/userGroups,libraries/api-client/src/self}':
    &a3
    .dir: camelCase
    .ts: camelCase
  '{libraries/api-client/src/client,libraries/api-client/src/user,libraries/api-client/src/conversation/data,libraries/api-client/src/team/conversation,libraries/api-client/src/team/data,libraries/api-client/src/team/scim,libraries/api-client/src/team/identityprovider,libraries/api-client/src/team/search,libraries/api-client/src/team/invitation,libraries/api-client/src/team/legalhold,libraries/api-client/src/team/service,libraries/api-client/src/team/team,libraries/api-client/src/team/payment,libraries/api-client/src/team/billing,libraries/api-client/src/team,libraries/core/src/account,libraries/core/src/connection,libraries/core/src/giphy,libraries/core/src/team,libraries/core/src/broadcast}': *a3
  '{libraries/core/src/client,libraries/core/src/errors,libraries/core/src/storage,libraries/core/src/test,libraries/core/src/conversation/content}': *a3
  '{apps/webapp/src/script/components/badge,apps/webapp/src/script/components/userList,apps/webapp/src/script/components/participantItemContent,apps/webapp/src/script/components/titleBar,apps/webapp/src/script/components/conversationListCell,libraries/core/src/messagingProtocols/proteus}':
    .dir: camelCase
  apps/webapp/src/script/page:
    .dir: camelCase
    .ts: camelCase
    .tsx: camelCase
    .test.ts: camelCase
    .test.tsx: camelCase
    .styles.ts: camelCase
  apps/webapp/src/script/repositories/tracking:
    .dir: camelCase
    .ts: camelCase
    .helpers.ts: camelCase
  libraries/api-client/src/types:
    .dir: camelCase
    .d.ts: camelCase
  '{libraries/api-client/src/tcp,libraries/core/src/notification,libraries/core/src/conversation/message,libraries/core/src/conversation/conversationService,libraries/core/src/messagingProtocols/proteus/utility,libraries/core/src/messagingProtocols/mls/e2eIdentityService}':
    .dir: camelCase
    .ts: camelCase
    .test.ts: camelCase
    .types.ts: camelCase
  '{libraries/api-client/src/asset,libraries/api-client/src/cells}':
    .dir: camelCase
    .ts: camelCase
    .test.ts: camelCase
    .schema.ts: camelCase
  libraries/api-client/src/notification:
    .dir: camelCase
    .ts: camelCase
    .test.ts: camelCase
    .mocks.ts: camelCase
  libraries/api-client/src/team/sso:
    .dir: camelCase
    .ts: camelCase
    .types.ts: camelCase
  libraries/api-client/src/team/feature:
    .dir: camelCase
    .ts: camelCase
    .schema.ts: camelCase
    .types.ts: camelCase
    .helper.ts: camelCase
  libraries/core/src/secretStore:
    .dir: camelCase
    .ts: camelCase
    .test.ts: camelCase
    .test.node.ts: camelCase
  libraries/core/src/messagingProtocols/proteus/proteusService/cryptoClient:
    .dir: camelCase
    .ts: camelCase
    .test.ts: camelCase
    .types.ts: camelCase
    .store.ts: camelCase
  libraries/core/src/messagingProtocols/proteus/proteusService:
    .ts: camelCase
    .test.ts: camelCase
    .types.ts: camelCase
    .mocks.ts: camelCase
  libraries/core/src/messagingProtocols/mls/mlsService:
    .ts: camelCase
    .test.ts: camelCase
    .types.ts: camelCase
  libraries/core/src/messagingProtocols/mls/e2eIdentityService/connection/acmeServer:
    .ts: camelCase
    .types.ts: camelCase
    .schema.ts: camelCase
  libraries/core/src/messagingProtocols/mls/e2eIdentityService/storage:
    .ts: camelCase
    .schema.ts: camelCase
  libraries/core/src/messagingProtocols/mls/e2eIdentityService/steps/dpopChallenge:
    .ts: camelCase
    .types.ts: camelCase
  libraries/react-ui-kit/src/images:
    .dir: camelCase
    .tsx: camelCase
  '{libraries/react-ui-kit/src/dataDisplay,libraries/react-ui-kit/src/identity}':
    .ts: camelCase
    .tsx: camelCase
    .styles.ts: camelCase
    .stories.tsx: camelCase
    .test.tsx: camelCase
  '{libraries/react-ui-kit/src/navigation,libraries/react-ui-kit/src/surface}':
    .dir: camelCase
    .ts: camelCase
    .tsx: camelCase
    .styles.ts: camelCase
    .stories.tsx: camelCase
    .test.tsx: camelCase
  libraries/react-ui-kit/src/layout:
    .dir: camelCase
    .ts: camelCase
    .tsx: camelCase
    .stories.tsx: camelCase
    .test.tsx: camelCase
  libraries/react-ui-kit/src/typography:
    .ts: camelCase
    .tsx: camelCase
    .style.ts: camelCase
    .stories.tsx: camelCase
    .test.tsx: camelCase
  libraries/react-ui-kit/src/utils:
    .ts: camelCase
    .tsx: camelCase
  libraries/react-ui-kit/src/inputs/{button,buttonGroup,buttonLink,buttonsGroup,checkbox,codeInput,comboboxSelect,datePickerField,dateTimePickerField,dropFileInput,errorMessage,form,iconButton,indicatorRangeInput,input,inputBlock,inputLabel,inputSubmitCombo,rangeInput,roundIconButton,secondaryButton,select,shakeBox,switch,textArea,timePickerField}:
    .ts: camelCase
    .tsx: camelCase
    .styles.ts: camelCase
    .stories.tsx: camelCase
    .test.tsx: camelCase
