ls:
  libraries/config/src:
    .dir: camelCase
    .ts: camelCase
    .spec.ts: camelCase
    .config.ts: camelCase
    .config.spec.ts: camelCase
    .types.ts: camelCase
  apps/server/routes:
    .dir: camelCase
    .ts: camelCase
    .test.ts: camelCase
  apps/server/util:
    .dir: camelCase
    .ts: camelCase
    .test.ts: camelCase
  libraries/api-client/src/broadcast:
    .dir: camelCase
    .ts: camelCase
  libraries/api-client/src/env:
    .dir: camelCase
    .ts: camelCase
  libraries/api-client/src/generic:
    .dir: camelCase
    .ts: camelCase
  libraries/api-client/src/services:
    .dir: camelCase
    .ts: camelCase
  libraries/api-client/src/federation/data:
    .dir: camelCase
    .ts: camelCase
  libraries/api-client/src/giphy:
    .dir: camelCase
    .ts: camelCase
  libraries/api-client/src/utils/backFromSleepHandler:
    .dir: camelCase
    .ts: camelCase
    .test.ts: camelCase
  libraries/api-client/src/validation:
    .dir: camelCase
    .ts: camelCase
  libraries/api-client/src/obfuscation:
    .dir: camelCase
    .ts: camelCase
    .test.ts: camelCase
  libraries/api-client/src/oauth:
    .dir: camelCase
    .ts: camelCase
  libraries/api-client/src/types:
    .dir: camelCase
    .d.ts: camelCase
