bracketSpacing: false
jsxBracketSameLine: false
printWidth: 120
proseWrap: false
requirePragma: false
semi: true
singleQuote: true
tabWidth: 2
trailingComma: es5
useTabs: false

overrides:
- files: "*.json"
  options:
    printWidth: 200
