arrowParens: avoid
bracketSpacing: false
jsxBracketSameLine: false
printWidth: 120
proseWrap: never
requirePragma: false
semi: true
singleQuote: true
tabWidth: 2
trailingComma: es5
useTabs: false

overrides:
- files: "*.json"
  options:
    printWidth: 200
- files: "app/script/localization/webapp.js"
  options:
    printWidth: 200
- files: "app/script/localization/translations/*.js"
  options:
    printWidth: 200
