extends: stylelint-config-recommended
rules:
  color-hex-case: lower
  color-hex-length: short
  font-family-name-quotes: always-where-required
  function-url-quotes: never
  number-leading-zero: never
  selector-attribute-quotes: always
  selector-type-no-unknown: null
  string-quotes: single
