extends: stylelint-config-standard
rules:
  color-hex-case: lower
  color-hex-length: short
  declaration-empty-line-before: never
  font-family-name-quotes: always-where-required
  function-url-quotes: never
  number-leading-zero: never
  number-no-trailing-zeros: null
  selector-attribute-quotes: always
  selector-type-no-unknown: null
  string-quotes: single
