compressionLevel: mixed

defaultSemverRangePrefix: ''

enableGlobalCache: false

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.16.0.cjs

approvedGitRepositories:
  - 'https://github.com/wireapp/amplify.git'

npmPreapprovedPackages:
  - '@wireapp/*'
