project_identifier: wire-cs
base_path: .

files:
  -
    source: '/app/script/localization/webapp.js'
    translation: '/app/script/localization/translations/webapp-%locale%.js'
    type: 'properties_play'
    update_option: 'update_as_unapproved'
  -
    source: 'temp/i18n/webapp.pot'
    translation: 'temp/i18n/webapp-%locale%.po'
    update_option: 'update_as_unapproved'
