api_key: <%= ENV['WIRE_CROWDIN_API_KEY'] %>

project_identifier: wire-cs
base_path: .

files:
  -
    source: '/app/script/localization/strings.coffee'
    translation: '/app/script/localization/strings-%two_letters_code%.coffee'
    ignore:
      - /**/?.pot
