/*
 * Wire
 * Copyright (C) 2024 Wire Swiss GmbH
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see http://www.gnu.org/licenses/.
 *
 */

export interface Countly {
  /**
   * Countly does not provide Typescript types, so we have to define the q array as any[].
   * The documentation for everything than can be pushed to q is here is linked above.
   */
  q: {
    push: (args: [EventType, ...any]) => void;
  };
  //  mandatory, app key for your app created in Countly
  app_key: string;
  // to identify a visitor, will be autogenerated if not provided
  device_id: string;
  // your Countly server URL - you may also use your own server URL or IP here
  url: string;
  // (optional) the version of your app or website
  app_version?: string;
  // (optional) country code for your visitor
  country_code?: string;
  // (optional) city for your visitor
  city?: string;
  // (optional) ip_address for your visitor
  ip_address?: string;
  // output debug info into the console (default: false)
  debug: boolean;
  // option to ignore traffic from bots (default: true)
  ignore_bots: boolean;
  // set an interval for how often inspections should be made to see if there is any data to report and then report it (default: 500 ms)
  interval: number;
  // the maximum amount of queued requests to store (default: 1000)
  queue_size: number;
  // set the time to wait in seconds after a failed connection to the server (default: 60 seconds)
  fail_timeout: number;
  // the time limit after which a user will be considered inactive if no actions have been made. No mouse movement, scrolling, or keys pressed. Expressed in minutes (default: 20 minutes)
  inactivity_time: number;
  // how often a session should be extended, expressed in seconds (default: 60 seconds)
  session_update: number;
  // maximum amount of events to send in one batch (default: 100)
  max_events: number;
  // the maximum amount of breadcrumbs to store for crash logs (default: 100)
  max_breadcrumb_count: number;
  // array with referrers to ignore (default: none)
  ignore_referrers: string[];
  // string salt for checksums (default: none)
  checksum_salt: string;
  // ignore prefetching and pre-rendering from counting as real website visits (default: true)
  ignore_prefetch: boolean;
  // Array of trusted domains (as string) that can trigger heatmap script loading. By default the SDK whitelists your server url.
  heatmap_whitelist: string[];
  // force using post method for all requests (default: false)
  force_post: boolean;
  // ignore this current visitor (default: false)
  ignore_visitor: boolean;
  // Pass true if you are implementing GDPR compatible consent management. This would prevent running any functionality without proper consent (default: false)
  require_consent: boolean;
  // object instructing which UTM parameters to track (default: {"source":true, "medium":true, "campaign":true, "term":true, "content":true})
  utm: {[key: string]: boolean};
  // use cookies to track sessions (default: true)
  use_session_cookie: boolean;
  // how long until a cookie session should expire, expressed in minutes (default: 30 minutes)
  session_cookie_timeout: number;
  // enable automatic remote config fetching, provide the callback function to be notified when fetching is complete (default: false)
  remote_config: boolean;
  // opts in the user for A/B testing while fetching the remote config (default: true)
  rc_automatic_optin_for_ab: boolean;
  // set it to true to use the explicit remote config API (default: false)
  use_explicit_rc_api: boolean;
  // have a separate namespace for persistent data when using multiple trackers on the same domain
  namespace: string;
  // Set to false to disable domain tracking, so no domain data would be reported (default: true)
  track_domains: boolean;
  // object to override or add headers to all SDK requests
  headers: {[key: string]: string};
  // What type of storage to use, by default uses local storage and would fallback to cookies, but you can set values "localstorage" or "cookies" to force only specific storage, or use "none" to not use any storage and keep everything in memory
  storage: 'localstorage' | 'cookies' | 'none';
  /**
   * provide metrics override or custom metrics for this user.
   * For more information on the specific metric keys used by Countly, check:
   * https://support.countly.com/hc/en-us/articles/9290669873305-A-Deeper-Look-at-SDK-concepts#setting-custom-user-metrics
   */
  metrics: {[key: string]: any};
  // initialize Countly tracking after setting the configuration
  init: () => void;

  offline_mode: boolean;
}

export type EventType =
  | 'add_consent'
  | 'add_event'
  | 'change_id'
  | 'begin_session'
  | 'end_session'
  | 'disable_offline_mode'
  | 'enable_offline_mode'
  | 'track_clicks'
  | 'track_performance'
  | 'track_pageview'
  | 'track_sessions'
  | 'track_scrolls'
  | 'track_links'
  | 'track_errors'
  | 'remove_consent'
  | 'userData.set'
  | 'userData.save';

/**
 * - `sessions`: Tracks when, how often, and how long users use your website.
 * - `events`: Allows your events to be sent to the server.
 * - `views`: Allows for the views/pages accessed by a user to be tracked.
 * - `scrolls`: Allows a user’s scrolls to be tracked on the heatmap.
 * - `clicks`: Allows a user’s clicks and link clicks to be tracked on the heatmap.
 * - `forms`: Allows a user’s form submissions to be tracked.
 * - `crashes`: Allows JavaScript errors to be tracked.
 * - `attribution`: Allows direct attribution tracking.
 * - `users`: Allows user information, including custom properties, to be collected/provided.
 * - `star-rating`: Allows user rating and feedback tracking through rating widgets.
 * - `feedback`: Allows survey, NPS, and rating widgets usage and reporting.
 * - `apm`: Allows performance tracking of the application by recording traces.
 * - `location`: Allows a user’s location (country, city area) to be recorded.
 * - `remote-config`: Allows users to download remote config from the server.
 */
export type CountlyConsentFeatures =
  | 'sessions'
  | 'events'
  | 'views'
  | 'scrolls'
  | 'clicks'
  | 'forms'
  | 'crashes'
  | 'attribution'
  | 'users'
  | 'star-rating'
  | 'feedback'
  | 'location'
  | 'remote-config'
  | 'apm';
