deploy:
  artifact: apps/server/dist/s3/ebs.zip
global:
  application_name: Webapp
  default_platform: Node.js 24 running on 64bit Amazon Linux 2023
  default_region: eu-central-1
  sc: git
  workspace_type: Application
