codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: '45...80'
  status:
    patch: off
    project:
      default:
        informational: true
        only_pulls: true

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: 'diff'
  behavior: default
  require_changes: no

github_checks:
  annotations: false
