apiVersion: v1
description: A Helm chart for the Wire webapp in Kubernetes
name: webapp
version: 0.4.0
annotations:
  # must conform to https://github.com/helm/community/blob/main/hips/hip-0015.md
  helm.sh/images: |
    - name: webapp
      image: quay.io/wire/webapp:do-not-use
