name: 'Bump webapp chart in wire-builds'
description: 'Bump webapp chart in wire-builds'
inputs:
  image_tag:
    description: 'tag of the docker image'
    required: true

  chart_version:
    description: 'version of the chart'
    required: true

  target_branch:
    description: 'the wire-builds branch to bump the webapp version in'
    required: true

  gh_token:
    description: 'GitHub token to use for pushing to wire-builds'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Check out wire-builds
      uses: actions/checkout@v4
      with:
        repository: wireapp/wire-builds
        token: ${{inputs.gh_token}}
        ref: ${{inputs.target_branch}}
        fetch-depth: 1

    - name: Create new build in wire-build
      shell: bash
      run: |
        set -eo pipefail

        chart_version="${inputs.chart_version}}"
        image_tag="${{inputs.image_tag}}"

        git config --global user.email "zebot@users.noreply.github.com"
        git config --global user.name "Zebot"

        for retry in $(seq 3); do
          (
          set -e

          if (( retry > 1 )); then
          echo "Retrying..."
          fi

          git fetch --depth 1 origin "${{ inputs.target_branch }}"
          git checkout "${{ inputs.target_branch }}"
          git reset --hard @{upstream}

          build_json=$(cat ./build.json | \
            ./bin/set-chart-fields webapp \
            "version=$chart_version" \
            "repo=https://s3-eu-west-1.amazonaws.com/public.wire.com/charts-webapp" \
            "meta.appVersion=$image_tag" \
            "meta.commitURL=${{github.event.head_commit.url}}" \
            "meta.commit=${{github.event.head_commit.id}}" \
            | ./bin/bump-prerelease )
          echo "$build_json" > ./build.json

          git add build.json
          git commit -m "Bump webapp to $chart_version"

          ) && break
        done
        if (( $? != 0 )); then
            echo "Retrying didn't help. Failing the step."
            exit 1
        fi
