/*
 * Wire
 * Copyright (C) 2016 Wire Swiss GmbH
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see http://www.gnu.org/licenses/.
 *
 */

/* eslint no-magic-numbers: "off" */

const CBOR = require('wire-webapp-cbor');

const ClassUtil = require('../util/ClassUtil');
const DontCallConstructor = require('../errors/DontCallConstructor');
const TypeUtil = require('../util/TypeUtil');

const DerivedSecrets = require('../derived/DerivedSecrets');
const MacKey = require('../derived/MacKey');
const MessageKeys = require('./MessageKeys');

/** @module session */

/**
 * @class ChainKey
 * @throws {DontCallConstructor}
 */
class ChainKey {
  constructor() {
    throw new DontCallConstructor(this);
  }

  /**
   * @param {!derived.MacKey} key - Mac Key generated by derived secrets
   * @param {!number} counter
   * @returns {ChainKey}
   */
  static from_mac_key(key, counter) {
    TypeUtil.assert_is_instance(MacKey, key);
    TypeUtil.assert_is_integer(counter);

    const ck = ClassUtil.new_instance(ChainKey);
    ck.key = key;
    ck.idx = counter;
    return ck;
  }

  /** @returns {ChainKey} */
  next() {
    const ck = ClassUtil.new_instance(ChainKey);
    ck.key = MacKey.new(this.key.sign('1'));
    ck.idx = this.idx + 1;
    return ck;
  }

  /** @returns {session.MessageKeys} */
  message_keys() {
    const base = this.key.sign('0');
    const derived_secrets = DerivedSecrets.kdf_without_salt(base, 'hash_ratchet');
    return MessageKeys.new(derived_secrets.cipher_key, derived_secrets.mac_key, this.idx);
  }

  /**
   * @param {!CBOR.Encoder} encoder
   * @returns {CBOR.Encoder}
   */
  encode(encoder) {
    encoder.object(2);
    encoder.u8(0);
    this.key.encode(encoder);
    encoder.u8(1);
    return encoder.u32(this.idx);
  }

  /**
   * @param {!CBOR.Decoder} decoder
   * @returns {ChainKey}
   */
  static decode(decoder) {
    TypeUtil.assert_is_instance(CBOR.Decoder, decoder);

    const self = ClassUtil.new_instance(ChainKey);

    const nprops = decoder.object();
    for (let index = 0; index <= nprops - 1; index++) {
      switch (decoder.u8()) {
        case 0:
          self.key = MacKey.decode(decoder);
          break;
        case 1:
          self.idx = decoder.u32();
          break;
        default:
          decoder.skip();
      }
    }

    TypeUtil.assert_is_instance(MacKey, self.key);
    TypeUtil.assert_is_integer(self.idx);

    return self;
  }
}

module.exports = ChainKey;
