/*
 * Wire
 * Copyright (C) 2025 Wire Swiss GmbH
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see http://www.gnu.org/licenses/.
 *
 */

/**
 * Type definitions and interfaces for the background effects system.
 *
 * This module exports all shared types used across the background effects pipeline,
 * including effect modes, quality settings, worker messages, and configuration options.
 */

/**
 * Effect mode for background processing.
 * - 'blur': Applies blur effect to the background
 * - 'virtual': Replaces background with an image or video
 * - 'passthrough': No processing, passes through original video
 */
export type EffectMode = 'blur' | 'virtual' | 'passthrough';

/**
 * Processing mode (excludes passthrough, as passthrough doesn't require processing).
 * Used by quality controller and renderer to determine processing parameters.
 */
export type Mode = Exclude<EffectMode, 'passthrough'>;

/**
 * Debug visualization mode for inspecting segmentation masks.
 * - 'off': Normal rendering with effects applied
 * - 'maskOverlay': Overlays green tint on mask areas
 * - 'maskOnly': Displays only the segmentation mask as grayscale
 * - 'edgeOnly': Highlights mask edges using edge detection
 * - 'classOverlay': Overlays class colors from multiclass segmentation
 * - 'classOnly': Shows class colors only (no video)
 */
export type DebugMode = 'off' | 'maskOverlay' | 'maskOnly' | 'edgeOnly' | 'classOverlay' | 'classOnly';

export type QualityTier = 'superhigh' | 'high' | 'medium' | 'low' | 'bypass';

/**
 * Quality mode for rendering performance.
 * - 'auto': Adaptive quality based on performance metrics
 * -  QualityTier
 */
export type QualityMode = 'auto' | QualityTier;

/**
 * Optional mapping of quality tiers to segmentation model paths.
 */
export type SegmentationModelByTier = Partial<Record<QualityTier, string>>;

/**
 * Browser capability information detected at runtime.
 */
export interface CapabilityInfo {
  offscreenCanvas: boolean;
  worker: boolean;
  webgl2: boolean;
  requestVideoFrameCallback: boolean;
}

export type QualityPolicyMode = 'auto' | 'conservative' | 'aggressive';

export interface QualityPolicyResult {
  initialTier: QualityTier;
  segmentationModelByTier?: SegmentationModelByTier;
}

export type QualityPolicyResolver = (capabilities: CapabilityInfo) => QualityPolicyResult;

/**
 * Rendering pipeline selection.
 * - 'worker-webgl2': OffscreenCanvas + WebGL2 in a Worker
 * - 'main-webgl2': WebGL2 on the main thread
 * - 'canvas2d': Canvas2D compositing fallback
 * - 'passthrough': No processing
 */
export type PipelineType = 'worker-webgl2' | 'main-webgl2' | 'canvas2d' | 'passthrough';

/**
 * Quality tier parameters that control rendering performance and visual quality.
 *
 * These parameters are generated by QualityController and used by WebGlRenderer
 * to configure the rendering pipeline. They balance visual quality against
 * performance by adjusting segmentation resolution, processing cadence, and
 * post-processing effects.
 */
export interface QualityTierParams {
  /** Quality tier identifier */
  tier: QualityTier;
  /** Segmentation mask width in pixels. Lower values reduce CPU/ML cost. */
  segmentationWidth: number;
  /** Segmentation mask height in pixels. Lower values reduce CPU/ML cost. */
  segmentationHeight: number;
  /** Segmentation cadence (process every Nth frame). Higher values reduce CPU/ML cost. */
  segmentationCadence: number;
  /** Scale factor for mask refinement pass (0-1). Lower values reduce GPU cost. */
  maskRefineScale: number;
  /** Scale factor for blur downsampling (0-1). Lower values reduce GPU cost. */
  blurDownsampleScale: number;
  /** Blur radius in pixels. Lower values reduce GPU cost. */
  blurRadius: number;
  /** Joint bilateral filter radius in pixels. Lower values reduce GPU cost. */
  bilateralRadius: number;
  /** Spatial sigma for joint bilateral filter. Controls spatial smoothing. */
  bilateralSpatialSigma: number;
  /** Range sigma for joint bilateral filter. Controls edge preservation. */
  bilateralRangeSigma: number;
  /** Lower threshold for soft matte edge (0-1). Controls where soft edges begin. */
  softLow: number;
  /** Upper threshold for soft matte edge (0-1). Controls where soft edges end. */
  softHigh: number;
  /** Lower threshold for matte cutoff (0-1). Pixels below this are considered background. */
  matteLow: number;
  /** Upper threshold for matte cutoff (0-1). Pixels above this are considered foreground. */
  matteHigh: number;
  /** Hysteresis value for matte thresholds to prevent flickering (0-1). */
  matteHysteresis: number;
  /** Temporal smoothing alpha (0-1). Higher values increase temporal stability. */
  temporalAlpha: number;
  /** If true, bypass all processing and pass through original frames. */
  bypass: boolean;
}

/**
 * Background source for virtual background mode (static image).
 *
 * Used internally by BackgroundEffectsController to store and manage
 * background images for virtual background replacement.
 */
export interface BackgroundSourceImage {
  /** Discriminator for type narrowing. */
  type: 'image';
  /** Image bitmap data (transferred to worker if using worker pipeline). */
  bitmap: ImageBitmap;
  /** Image width in pixels. */
  width: number;
  /** Image height in pixels. */
  height: number;
}

/**
 * Background source for virtual background mode (video frame).
 *
 * Used internally by BackgroundEffectsController to store and manage
 * background video frames for virtual background replacement.
 */
export interface BackgroundSourceVideoFrame {
  /** Discriminator for type narrowing. */
  type: 'video';
  /** Video frame bitmap data (transferred to worker if using worker pipeline). */
  bitmap: ImageBitmap;
  /** Frame width in pixels. */
  width: number;
  /** Frame height in pixels. */
  height: number;
}

/**
 * Performance metrics tracked during frame processing.
 *
 * These metrics are collected by the worker/main thread and sent to the
 * main thread for monitoring and adaptive quality control. Averages are
 * computed over a rolling window of recent frames.
 *
 * **Important**: These metrics measure **time allocation** (wall-clock time
 * spent in each phase), not actual hardware CPU/GPU utilization. The percentages
 * indicate what portion of total processing time was spent in each phase.
 *
 * - `avgSegmentationMs`: Time spent in ML segmentation (may run on CPU or GPU
 *   depending on delegate type, see `segmentationDelegate`)
 * - `avgGpuMs`: Time spent in WebGL rendering operations (runs on GPU)
 */
export interface Metrics {
  /** Average total frame processing time in milliseconds (segmentation + WebGL rendering). */
  avgTotalMs: number;
  /** Average ML segmentation time in milliseconds. */
  avgSegmentationMs: number;
  /** Average WebGL rendering time in milliseconds. */
  avgGpuMs: number;
  /** Segmentation delegate type ('CPU' or 'GPU') indicating where segmentation runs. */
  segmentationDelegate: 'CPU' | 'GPU' | null;
  /** Number of frames dropped due to processing errors or timeouts. */
  droppedFrames: number;
  /** Current quality tier */
  tier: QualityTier;
}

/**
 * Configuration options for starting the background effects pipeline.
 *
 * All options are optional and have sensible defaults. Used when calling
 * BackgroundEffectsController.start() to configure the processing pipeline.
 */
export interface StartOptions {
  /** Target frames per second for adaptive quality control. Default: 30. */
  targetFps?: number;
  /** Quality mode  Default: 'auto'. */
  quality?: QualityMode;
  /** Debug visualization mode. Default: 'off'. */
  debugMode?: DebugMode;
  /** Effect mode ('blur', 'virtual', or 'passthrough'). Default: 'blur'. */
  mode?: EffectMode;
  /** Blur strength (0-1) for blur effect mode. Default: 0.5. */
  blurStrength?: number;
  /** Background image for virtual background mode (HTMLImageElement or ImageBitmap). */
  backgroundImage?: HTMLImageElement | ImageBitmap;
  /** Background video element for virtual background mode. */
  backgroundVideo?: HTMLVideoElement;
  /** Solid background color for virtual background mode (CSS color string). */
  backgroundColor?: string;
  /** Path to MediaPipe segmentation model file. */
  segmentationModelPath?: string;
  /** Per-tier segmentation model overrides (e.g., Tier A uses multiclass). */
  segmentationModelByTier?: SegmentationModelByTier;
  /** Optional device capability policy for tier/model selection. */
  qualityPolicy?: QualityPolicyMode | QualityPolicyResolver;
  /** Whether to prefer worker-based pipeline when available. Default: true. */
  useWorker?: boolean;
  /** Override pipeline selection (primarily for testing). */
  pipelineOverride?: PipelineType;
  /** Optional callback to receive performance metrics updates. */
  onMetrics?: (metrics: Metrics) => void;
  /** Optional callback to receive model name updates. */
  onModelChange?: (model: string) => void;
}

/**
 * Worker initialization message sent from main thread to worker.
 *
 * Transfers OffscreenCanvas control to the worker and provides initial
 * configuration. The canvas is transferred (not cloned) for performance.
 */
export interface WorkerInitMessage {
  /** Message type discriminator. */
  type: 'init';
  /** OffscreenCanvas for WebGL rendering (transferred, not cloned). */
  canvas: OffscreenCanvas;
  /** Initial canvas width in pixels. */
  width: number;
  /** Initial canvas height in pixels. */
  height: number;
  /** Device pixel ratio for high-DPI displays. */
  devicePixelRatio: number;
  /** Required worker options (all fields must be provided). */
  options: Required<WorkerOptions>;
}

/**
 * Worker frame message sent from main thread to worker.
 *
 * Transfers a video frame (ImageBitmap) to the worker for processing.
 * The frame is transferred (not cloned) for performance. The worker
 * responds with 'frameProcessed' when done.
 */
export interface WorkerFrameMessage {
  /** Message type discriminator. */
  type: 'frame';
  /** Video frame as ImageBitmap (transferred, not cloned). */
  frame: ImageBitmap;
  /** Frame timestamp in seconds (from video source). */
  timestamp: number;
  /** Frame width in pixels. */
  width: number;
  /** Frame height in pixels. */
  height: number;
}

/**
 * Worker update message for runtime configuration changes.
 *
 * Used to update worker state without reinitializing. Different message
 * types require different optional fields based on the update type.
 */
export interface WorkerUpdateMessage {
  /** Message type discriminator. Determines which optional fields are used. */
  type:
    | 'setMode'
    | 'setBlurStrength'
    | 'setDebugMode'
    | 'setQuality'
    | 'setBackgroundImage'
    | 'setBackgroundVideo'
    | 'setDroppedFrames'
    | 'stop';
  /** New effect mode (for 'setMode'). */
  mode?: EffectMode;
  /** New blur strength 0-1 (for 'setBlurStrength'). */
  blurStrength?: number;
  /** New debug mode (for 'setDebugMode'). */
  debugMode?: DebugMode;
  /** New quality mode (for 'setQuality'). */
  quality?: QualityMode;
  /** Background image bitmap (for 'setBackgroundImage', transferred). */
  image?: ImageBitmap;
  /** Background video frame bitmap (for 'setBackgroundVideo', transferred). */
  video?: ImageBitmap;
  /** Width in pixels (for 'setBackgroundImage'/'setBackgroundVideo'). */
  width?: number;
  /** Height in pixels (for 'setBackgroundImage'/'setBackgroundVideo'). */
  height?: number;
  /** Dropped frame count (for 'setDroppedFrames'). */
  droppedFrames?: number;
}

/**
 * Union type of all messages sent from main thread to worker.
 *
 * Used for type-safe message handling in the worker's onmessage handler.
 */
export type WorkerMessage = WorkerInitMessage | WorkerFrameMessage | WorkerUpdateMessage;

/**
 * Worker metrics message sent from worker to main thread.
 *
 * Sent periodically (after each frame) to provide performance metrics
 * for monitoring and adaptive quality control.
 */
export interface WorkerMetricsMessage {
  /** Message type discriminator. */
  type: 'metrics';
  /** Current performance metrics. */
  metrics: Metrics;
}

/**
 * Worker ready message sent from worker to main thread.
 *
 * Sent once after initialization completes, indicating the worker is
 * ready to process frames.
 */
export interface WorkerReadyMessage {
  /** Message type discriminator. */
  type: 'ready';
}

/**
 * Worker frame processed message sent from worker to main thread.
 *
 * Sent after each frame is processed, used for backpressure control
 * to prevent unbounded frame queues.
 */
export interface WorkerFrameProcessedMessage {
  /** Message type discriminator. */
  type: 'frameProcessed';
}

/**
 * Worker error message sent from worker to main thread.
 *
 * Sent when segmenter initialization fails. The worker continues in
 * bypass mode (no segmentation) but notifies the main thread.
 */
export interface WorkerSegmentErrorMessage {
  /** Message type discriminator. */
  type: 'segmenterError';
  /** Error message describing the failure. */
  error: string;
}

/**
 * Worker context lost message sent from worker to main thread.
 *
 * Sent when the worker's WebGL context is lost so the main thread can
 * decide how to recover (e.g., fallback to passthrough).
 */
export interface WorkerContextLostMessage {
  /** Message type discriminator. */
  type: 'contextLost';
}

export interface WorkerErrorMessage {
  /** Message type system error. */
  type: 'workerError';
  message: string;
  reason: string;
  filename?: string;
  lineno?: number;
  colno?: number;
}

/**
 * Union type of all messages sent from worker to main thread.
 *
 * Used for type-safe message handling in the main thread's worker.onmessage handler.
 */
export type WorkerResponse =
  | WorkerMetricsMessage
  | WorkerReadyMessage
  | WorkerFrameProcessedMessage
  | WorkerSegmentErrorMessage
  | WorkerErrorMessage
  | WorkerContextLostMessage;

/**
 * Required worker options for initialization.
 *
 * All fields are required (unlike StartOptions which has defaults).
 * Used internally when transferring options to the worker thread.
 */
export interface WorkerOptions {
  /** Effect mode ('blur', 'virtual', or 'passthrough'). */
  mode: EffectMode;
  /** Debug visualization mode. */
  debugMode: DebugMode;
  /** Quality mode ('auto' or fixed tier). */
  quality: QualityMode;
  /** Blur strength (0-1) for blur effect mode. */
  blurStrength: number;
  /** Path to MediaPipe segmentation model file. */
  segmentationModelPath: string;
  /** Per-tier segmentation model overrides (resolved in worker). */
  segmentationModelByTier: SegmentationModelByTier;
  /** Initial tier used when quality is set to auto. */
  initialTier: QualityTier;
  /** Target frames per second for adaptive quality control. */
  targetFps: number;
}
