name: 'Betterer - strict TS'
on: [push]

jobs:
  betterer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use latest Node.js v16
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Yarn cache
        uses: c-hive/gha-yarn-cache@v2.1.0

      - name: Install JS dependencies
        run: yarn --frozen-lockfile

      - name: Test TS regression
        run: yarn betterer ci
