name: Dependabot auto-merge
on: pull_request_target

permissions:
  pull-requests: write
  contents: write

jobs:
  activate-auto-merge:
    runs-on: ubuntu-latest
    if: ${{github.actor == 'dependabot[bot]'}}
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1.6.0
        with:
          github-token: '${{secrets.WEBTEAM_AUTOMERGE_TOKEN}}'

      # Add the auto-merge flag if the PR is a minor or patch version update
      - name: Enable auto-merge for minor and patch updates
        if: ${{steps.metadata.outputs.update-type == 'version-update:semver-minor' || steps.metadata.outputs.update-type == 'version-update:semver-patch'}}
        run: gh pr edit ${{ github.event.pull_request.id }} --add-label auto-merge
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
