name: Deploys to testing environments

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'The environment the branch should be deployed to'
        required: true
        type: choice
        options:
          - wire-webapp-qa
          - wire-webapp-mls

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      DEPLOYMENT_RECOVERY_TIMEOUT_SECONDS: 150
      AWS_APPLICATION_NAME: Webapp
      AWS_BUILD_ZIP_PATH: apps/server/dist/s3/ebs.zip
      AWS_REGION: eu-central-1

    steps:
      - name: Print environment variables
        run: |
          echo -e "branch = ${GITHUB_REF_NAME}"
          echo -e "env = ${ENV}"
        env:
          ENV: ${{ inputs.env }}

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: Setup Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'

      - name: Install JS dependencies
        run: yarn --immutable

      - name: Build and package
        run: yarn nx run server:package

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@ec61189d14ec14c8efccab744f656cffd0e33f37
        with:
          aws-access-key-id: ${{ secrets.WEBTEAM_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.WEBTEAM_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy to Elastic Beanstalk
        id: deploy
        uses: aws-actions/aws-elasticbeanstalk-deploy@1f56e4e813ae4eb167e69ca324234c336c1df573
        with:
          aws-region: ${{ env.AWS_REGION }}
          application-name: ${{ env.AWS_APPLICATION_NAME }}
          environment-name: ${{ inputs.env }}
          version-label: ${{ github.run_id }}
          deployment-package-path: ${{ env.AWS_BUILD_ZIP_PATH }}
          wait-for-deployment: false
          wait-for-environment-recovery: true
          deployment-timeout: ${{ env.DEPLOYMENT_RECOVERY_TIMEOUT_SECONDS }}
          use-existing-application-version-if-available: true
