name: E2E Tests Nightly

on:
  workflow_dispatch:
  schedule:
    # we want to run this nightly on dev
    - cron: '0 02 * * 1-5'

# Only allow one instance of this workflow to run per branch at a time
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  e2e_tests:
    name: Run e2e tests
    uses: ./.github/workflows/e2e-tests.yml
    with:
      webappUrl: https://wire-webapp-dev.zinfra.io/
      backendUrl: https://staging-nginz-https.zinfra.io/
    secrets:
      OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
      WIRE_E2E_TEST_BOT_WEBHOOK_URL: ${{ secrets.WIRE_E2E_TEST_BOT_WEBHOOK_URL }}

  report:
    name: Report test results
    if: ${{ !cancelled() }}
    runs-on: ubuntu-24.04
    needs: e2e_tests

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false

      - name: Add repository Yarn wrapper to PATH
        run: echo "$GITHUB_WORKSPACE/bin" >> "$GITHUB_PATH"

      - name: Setup Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'

      - name: Download report
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c
        with:
          artifact-ids: ${{ needs.e2e_tests.outputs.reportArtifactId }}
          path: apps/webapp/playwright-report
          pattern: '**/report.json'

      - name: Generate report description
        id: generate-description
        run: |
          REPORT_FILE="apps/webapp/playwright-report/report.json"
          if [ ! -f "$REPORT_FILE" ]; then
              echo "Error: File '$REPORT_FILE' not found!"
              exit 1
          fi

          FAILED=$(jq '.stats.unexpected' "$REPORT_FILE")
          MESSAGE=$(jq -c '
            # Recursively find all objects that have a non-empty "specs" array
            # Capture the suite title and prepend it to the test title
            [.. | objects | select(has("specs") and (.specs | length > 0)) | .title as $suite | .specs[] | .title as $title | .tests[] | {title: ($suite + " > " + $title), status: .status}] as $tests |
            
            # Calculate aggregates
            ($tests | length) as $total |
            ($tests | map(select(.status == "expected")) | length) as $passed |
            ($tests | map(select(.status == "unexpected")) | length) as $failed |
            ($tests | map(select(.status == "flaky")) | length) as $flaky |
            ($tests | map(select(.status == "skipped")) | length) as $skipped |
            
            # Generate unique lists for failed and flaky tests
            ($tests | map(select(.status == "unexpected")) | map("  ❌ " + .title) | unique | join("\n")) as $failed_list |
            ($tests | map(select(.status == "flaky")) | map("  ⚠️ " + .title) | unique | join("\n")) as $flaky_list |
            
            # Construct the final formatted message
            "📋 **Web E2E Test Run Summary**\n" +
            "Build URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}\n" +
            "======================================\n" +
            "**Total Tests:** \($total)\n" +
            "✅ **Passed:** \($passed)\n" +
            "❌ **Failed:** \($failed)\n" +
            "⚠️ **Flaky:** \($flaky)\n" +
            (if $skipped > 0 then "⏭️ **Skipped:** \($skipped)\n" else "" end) +
            "======================================\n" +
            (if $failed > 0 then "\n❌ **Failed Tests:**\n\($failed_list)\n" else "" end) +
            (if $flaky > 0 then "\n⚠️ **Flaky Tests:**\n\($flaky_list)\n" else "" end)
          ' $REPORT_FILE)

          echo "failed_tests=$FAILED" >> $GITHUB_OUTPUT
          echo "report_message=$MESSAGE" >> $GITHUB_OUTPUT

      - name: Upload report to Testiny
        continue-on-error: true
        env:
          TESTINY_API_KEY: ${{ secrets.TESTINY_API_KEY }}
          TESTINY_TEST_PLAN_ID: 105 # 105 is the id of the "Regression" test plan within Testiny
          DESCRIPTION: ${{ steps.generate-description.outputs.report_message }}
        run: |
          # Extract description from json format so it can be quoted correctly
          RAW_DESCRIPTION=$(echo "$DESCRIPTION" | jq -r '.')

          node ./apps/webapp/test/e2e_tests/scripts/uploadTestReport.ts \
          --runName="Regression $(date +'%m/%d/%Y - %H:%M')" \
          --testPlanId="$TESTINY_TEST_PLAN_ID" \
          --description="$RAW_DESCRIPTION" \
          --reportPath="./apps/webapp/playwright-report/report.json"

      - name: Notify on Wire about failed tests
        if: ${{ !cancelled() && steps.generate-description.outputs.failed_tests > 0 }}
        uses: 8398a7/action-slack@293f8dc0f9731ac35321056641cdef895f4f65f8
        continue-on-error: true
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.WIRE_E2E_TEST_BOT_WEBHOOK_URL }}
        with:
          status: custom
          custom_payload: |
            {
              "text": ${{ steps.generate-description.outputs.report_message }},
            }
