name: Generate test reports

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Git branch to generate the test report for'
        required: true
        type: string

jobs:
  generate_test_report:
    runs-on: ubuntu-latest

    env:
      UNIT_TEST_REPORT_FILE: './unit-tests.log'

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          ref: refs/heads/${{ inputs.branch }}

      - name: Capture checked out commit SHA
        run: echo "TESTED_COMMIT_SHA=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: Set TITLE
        env:
          PR_TITLE: ${{github.event.pull_request.title || env.COMMIT_MESSAGE}}
        run: echo "TITLE=$PR_TITLE" >> $GITHUB_ENV

      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@d07a454dad7609a92316b57b23c9ccfd4f59af66
        with:
          access_token: ${{github.token}}

      - name: Setup Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'

      - name: Authenticate git clone
        env:
          GH_TOKEN: ${{secrets.OTTO_THE_BOT_GH_TOKEN}}
        run: echo -e "machine github.com\n  login ${GH_TOKEN}" > ~/.netrc

      - name: Install JS dependencies
        run: yarn --immutable

      - name: Test
        run: |
          set -euo pipefail
          : > ${{ env.UNIT_TEST_REPORT_FILE }}
          (
            cd ./apps/server
            node ../../node_modules/jest/bin/jest.js --config jest.config.js --coverage --coverageReporters=lcov
          ) 2>&1 | tee -a ${{ env.UNIT_TEST_REPORT_FILE }}
          (
            cd ./apps/webapp
            node ../../node_modules/jest/bin/jest.js --config jest.report.config.cjs --coverage --coverageReporters=lcov --verbose
          ) 2>&1 | tee -a ${{ env.UNIT_TEST_REPORT_FILE }}
          echo -e "BRANCH = ${{ inputs.branch }}" >> ${{ env.UNIT_TEST_REPORT_FILE }}
          echo -e "COMMIT SHA = ${TESTED_COMMIT_SHA}" >> ${{ env.UNIT_TEST_REPORT_FILE }}
          echo -e "TEST RUN DATE = $(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> ${{ env.UNIT_TEST_REPORT_FILE }}

      - name: Upload unit-tests.log to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-west-1
        run: |
          TIMESTAMP=$(date -u +'%Y%m%dT%H%M%SZ')
          aws s3 cp ${{ env.UNIT_TEST_REPORT_FILE }} s3://wire-webapp/unit-tests-${TIMESTAMP}-${TESTED_COMMIT_SHA}.log
