name: Playwright Smoke Tests

on:
  workflow_dispatch:

jobs:
  smoke-tests:
    name: Run Playwright Smoke Tests
    if: github.repository == 'wireapp/wire-webapp'
    runs-on: [self-hosted, Linux, X64, office]

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Setup Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f
        with:
          node-version-file: '.nvmrc'

      - name: Enable Corepack
        run: corepack enable

      - name: Install JS dependencies
        run: yarn --immutable

      - name: Install Playwright browsers
        run: yarn playwright install --only-shell --with-deps chromium

      - name: Install 1Password
        uses: 1password/install-cli-action@8d006a0d0a4fd505af7f7ce589e7f768385ff5e4

      - name: Generate env file
        run: op inject -i apps/webapp/test/e2e_tests/.env.staging.tpl -o apps/webapp/test/e2e_tests/.env
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

      - name: Run smoke tests
        run: yarn nx run webapp:e2e --grep "@smoke"

      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: playwright-report
          path: playwright-report/
