name: Playwright Cells Critical Flow Tests scheduled

on:
  schedule:
    # Berlin 9 AM = 7 AM UTC in summer
    - cron: '0 7 * * *'

jobs:
  cells-crit-flow-tests-scheduled:
    strategy:
      matrix:
        environment: [imai, fulu, staging]
    uses: ./.github/workflows/run-cells-crit-flow-e2e-tests.yml
    with:
      environment: ${{ matrix.environment }}
    secrets:
      OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
