name: Playwright Cells Critical Flow Tests

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment'
        required: true
        type: choice
        options:
          - imai
          - fulu
          - staging
        default: staging

  schedule:
    # Berlin 9 AM = 7 AM UTC in summer
    - cron: '0 7 * * *'

jobs:
  # Scheduled: runs all 3 environments via matrix
  cells-crit-flow-tests-scheduled:
    if: github.event_name == 'schedule'
    strategy:
      matrix:
        environment: [imai, fulu, staging]
    uses: ./.github/workflows/run-cells-crit-flow-e2e-tests.yml
    with:
      environment: ${{ matrix.environment }}
    secrets:
      OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

  # Manual: runs single environment via input
  cells-crit-flow-tests-manual:
    if: github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/run-cells-crit-flow-e2e-tests.yml
    with:
      environment: ${{ github.event.inputs.environment }}
    secrets:
      OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
