name: Playwright Cells Critical Flow Tests

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment'
        required: true
        type: choice
        options:
          - imai
          - fulu
          - staging
        default: staging

  schedule:
    # runs on all three of the environments (in the morning, 9:00 Berlin summer time)
    - cron: '0 7 * * *'

jobs:
  smoke-tests:
    name: Run Playwright Cells Critical Flow Tests
    if: github.repository == 'wireapp/wire-webapp'
    runs-on: [self-hosted, Linux, X64, office]

    # Strategy is only used for scheduled runs, for manual runs the selected environment is used
    strategy:
      matrix:
        environment: >-
          ${{ github.event_name == 'schedule'
              && fromJson('["imai","fulu","staging"]')
              || fromJson(format('["{0}"]', github.event.inputs.environment)) }}


    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.16.x
          cache: 'yarn'

      - name: Install JS dependencies
        run: yarn --immutable

      - name: Install Playwright browsers
        run: yarn playwright install --with-deps && yarn playwright install chrome

      - name: Install 1Password
        uses: 1password/install-cli-action@v1

      - name: Generate env file
        run: op inject -i test/e2e_tests/.env.${{ github.event.inputs.environment }}.tpl -o test/e2e_tests/.env
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

      - name: Run critical flow tests
        run: yarn e2e-test --grep "@crit-flow-cells"

      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
