name: auto-merge PR
on: pull_request

permissions:
  pull-requests: write
  contents: write

# This job will enable auto merge on otto-the-bot's PRs
jobs:
  activate-auto-merge:
    runs-on: ubuntu-24.04
    if: ${{github.actor == 'otto-the-bot'}}
    steps:
      - name: Approve PR
        if: ${{ github.actor == 'otto-the-bot' }}
        run: gh pr review --approve "$PR_URL"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          PR_URL: ${{github.event.pull_request.html_url}}

      - name: Enable auto-merge
        if: ${{github.actor == 'otto-the-bot' || (github.event.pull_request.labels && contains(github.event.pull_request.labels.*.name, 'publish-to-npm')) }}
        run: |
          gh pr merge --auto --squash "$PR_URL"
        env:
          GITHUB_TOKEN: ${{secrets.OTTO_THE_BOT_GH_TOKEN}}
          PR_URL: ${{github.event.pull_request.html_url}}
