name: Pull Request

on:
  pull_request

jobs:
  # Automatically labels based on files changed
  label:
    name: Label PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Get commit message
        id: commit
        run: |
          COMMIT_MESSAGE=$(git log --format=%B -n 1 ${{github.event.after}})
          echo "::set-env name=COMMIT_MESSAGE::${COMMIT_MESSAGE}"
      - uses: srvaroa/labeler@v0.3
        env:
          GITHUB_TOKEN: ${{secrets.GH_TOKEN }}
  # Automatically rebases on request
  rebase:
    name: Rebase
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/rebase')
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Automatic Rebase
      uses: cirrus-actions/rebase@1.3.1
      env:
        GITHUB_TOKEN: ${{secrets.GH_TOKEN }}
