name: Rebase PR on request

on:
  issue_comment:
    types: [created, edited]

jobs:
  rebase:
    name: Rebase
    if: contains(github.event.comment.html_url, '/pull/') &&
      startsWith(github.event.comment.body, '/rebase') &&
      (github.event.comment.author_association == 'MEMBER' ||
      github.event.comment.author_association == 'OWNER')
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Automatic Rebase
      uses: cirrus-actions/rebase@1.3.1
      env:
        GITHUB_TOKEN: ${{secrets.GH_TOKEN}}
