name: Rebase PR

on:
  issue_comment:
    types:
      - created

jobs:
  # Automatically rebases on request
  rebase:
    name: Rebase
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '@otto-the-bot rebase')
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Automatic Rebase
      uses: cirrus-actions/rebase@1.3.1
      env:
        GITHUB_TOKEN: ${{secrets.GH_TOKEN }}
